### ISSUE TITLE
Non-persistent server resource pack load order.

### ISSUE THREAD

**Issue by Haano137** [TheMysterys/Server-Pack-Unlocker#3]
Leaving and rejoining a server does not make the resource pack stay in the same order you placed it in. It would be neat if server resource packs would be something you can see and move and all times in the Resource Packs options regardless whether you're in a server or not.

**Comment by TheMysterys** [comment]
When leaving a server the resource pack becomes unavailable to the client (at least from what I understand of the system), meaning they get removed from the list. 
Because of this it's not possible to keep the pack loaded after leaving the server. While you can still access them from the `server-resource-packs` folder, the mod does not. 

Though I might be miss-interpreting your suggestion so feel free to explain in more detail if you would like to.

**Comment by Andre601** [comment]
How I understand it is, that the mod "forgets" the order of RPs you had.

Like if you put a Resource pack above the server one, leave the server (or quit game) and then rejoin, the Server pack is at the top again, forcing you to put the other RP at the top again.
Quite tedious and useless to have like this.

My suggestion, if doable of course, would be to keep a list of the packs you put above the server pack for that particular server somewhere (i.e. in a configuration file), so that the mod remembers what RPs were above the server pack to then apply... Whether this can be done before the SP is loaded (to avoid duplicate loads) is something beyond my understanding.

**Comment by TheMysterys** [comment]
So currently the ordering of resource packs is controlled by the client (mainly cause I don't know how to handle that through the mod). Because of this, when the client downloads a server resource pack, it's code tells it to pin the pack and put it at the top. 

What the mod does is it overrides the code that pins the pack (which then allows players to move the pack around). Because the mod has no control over the ordering (nor keeps track of the ordering, which again not sure how I would implement at this time) the server resource pack will always default to being the top pack in the list.

**Comment by TheMysterys** [comment]
Hey guys, I'm happy to announce that I've finally got this working. Will be releasing the update in a few minutes. Just testing some edge cases

**Comment by IlIlIlIIlIlIlIl** [comment]
> Hey guys, I'm happy to announce that I've finally got this working. Will be releasing the update in a few minutes. Just testing some edge cases

its not working in 1.20.2
